name: "AWS Infrastructure Management"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "実行するアクションを選択（手動実行時のみ有効）"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

  schedule:
    # 平日 JST 08:50 (UTC 23:50 前日)
    - cron: '50 23 * * 1-5'

    # 平日 JST 19:05 (UTC 10:05 当日)
    - cron: '5 10 * * 1-5'

jobs:
  terraform:
    name: "Terraform Apply or Destroy"
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: "infra/environments/dev"

    outputs:
      schedule: ${{ steps.set-schedule.outputs.schedule }}
      action: ${{ steps.set-action.outputs.action }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Schedule
        id: set-schedule
        run: |
          echo "schedule=${{ github.event.schedule }}" >> $GITHUB_OUTPUT

      - name: Set Action Output
        id: set-action
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "action=${{ github.event.inputs.action }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.schedule }}" == "5 10 * * 1-5" ]]; then
            echo "action=destroy" >> $GITHUB_OUTPUT
          else
            echo "action=apply" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Execution
        run: |
          SCHEDULE="${{ github.event.schedule }}"
          INPUT_ACTION="${{ github.event.inputs.action }}"

          if [[ "$SCHEDULE" == "50 23 * * 0-4" ]]; then
            echo "Weekday Morning: Running Apply"
            terraform apply -auto-approve

          elif [[ "$SCHEDULE" == "5 10 * * 1-5" ]]; then
            echo "Weekday Evening: Running Destroy"
            terraform destroy -auto-approve

          elif [[ "$INPUT_ACTION" == "destroy" ]]; then
            echo "Manual Trigger: Running Destroy"
            terraform destroy -auto-approve

          else
            echo "Manual Trigger: Running Apply"
            terraform apply -auto-approve
          fi
        working-directory: ${{ env.WORKING_DIR }}

  deploy-app:
    name: "Trigger App Deployment"
    needs: terraform

    # 以下のいずれかの条件を満たす場合のみデプロイを実行
    # 1. 朝の自動applyスケジュールであること
    # 2. 手動実行（scheduleが空）かつ、選択したアクションが 'apply' であること
    if: |
      needs.terraform.outputs.schedule == '50 23 * * 0-4' ||
      (needs.terraform.outputs.schedule == '' && needs.terraform.outputs.action == 'apply')

    uses: ./.github/workflows/deploy.yml
    secrets: inherit
